"""Human and LLM references from the same metadata and authoring facts."""
from __future__ import annotations

import json

from .completion import attribute_description, attributes_for
from .facts import EXAMPLES, GRAMMAR, LIMITS, MISTAKES


def _cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def markup_reference(description: dict) -> str:
    lines = ["# Markup Reference", "", "Generated by `textui spec`; edit registry metadata or authoring facts, then regenerate.",
             "", "## Project and component grammar", "", GRAMMAR.strip(), "", "## Validation and schema limits", "", LIMITS.strip(),
             "", "## Document rules", ""]
    for rule in description["document_rules"]:
        lines.append(f"- **{rule['name']}** ({rule['phase']}): {rule['doc']}")
    lines.extend(["", "## Elements", ""])
    for component in description["components"]:
        lines.extend([f"### `<{component['tag']}>`", "",
                      f"Text: **{component['text_policy']}**. Child policy: **{component['content']['policy']}**.", ""])
        attributes = attributes_for(component, description["common_attributes"])
        if attributes:
            lines.extend(["| Attribute | Type, requirement and default |", "| --- | --- |"])
            for name, attr in attributes.items():
                lines.append(f"| `{name}` | {_cell(attribute_description(attr))} |")
            lines.append("")
        if component["events"]:
            lines.append("Events (Python action identifiers):")
            lines.append("")
            lines.extend(f"- `on-{name}`: `{event['message_type']}`" for name, event in component["events"].items())
            lines.append("")
        if component["content"]["rules"]:
            lines.append("Content rules (compound and phase-specific rules remain explicit):")
            lines.append("")
            for rule in component["content"]["rules"]:
                label = rule.get("name", rule["rule"])
                detail = rule.get("doc", rule.get("message", ""))
                fields = {key: value for key, value in rule.items() if key not in {"rule", "name", "doc", "message", "phase"}}
                lines.append(f"- **{label}** ({rule['phase']}): {detail}" + (f" `{json.dumps(fields, ensure_ascii=False)}`" if fields else ""))
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def llm_reference(description: dict) -> str:
    lines = ["# TextUI LLM Authoring Reference", "", "Generated by `textui spec`. Install `textui-markup`; import and CLI name: `textui`.",
             "", "## Grammar", "", GRAMMAR.strip(), "", "## Check generated markup", "",
             "```sh", "textui check --static --format json app.ui", "```", "", LIMITS.strip(),
             "", "## Element table", "", "| Element | Text / children | Attributes | Events |", "| --- | --- | --- | --- |"]
    for component in description["components"]:
        attrs = attributes_for(component, description["common_attributes"])
        attr_text = "; ".join(f"`{name}`: {attribute_description(attr)}" for name, attr in attrs.items())
        events = ", ".join(f"`on-{name}`" for name in component["events"])
        lines.append(f"| `{component['tag']}` | {component['text_policy']} / {component['content']['policy']} | {_cell(attr_text)} | {events or 'None'} |")
    lines.extend(["", "## Explicit structural rules", ""])
    for component in description["components"]:
        for rule in component["content"]["rules"]:
            lines.append(f"- `{component['tag']}`: `{json.dumps(rule, ensure_ascii=False)}`")
    lines.extend(["", "## Canonical examples", "",
                  "Copied verbatim from repository examples. Save component pairs together; the component app also links",
                  "`controller.py` from its example directory, which exposes the `open_alpha` action. Static checking requires",
                  "that local script file to exist but does not execute it. Form actions require host callback binding.", ""])
    for path, markup in EXAMPLES.items():
        lines.extend([f"### `{path}`", "", "```xml", markup.rstrip(), "```", ""])
    lines.extend(["## Common mistakes", "", "These invalid documents are pinned to loader regression tests.", ""])
    for title, markup, message in MISTAKES:
        lines.extend([f"### {title}", "", "```xml", markup, "```", "", f"Diagnostic contains: `{message}`.", ""])
    return "\n".join(lines).rstrip() + "\n"
