"""Bounded XML Schema profiles generated from declarative registry metadata."""
from __future__ import annotations

from lxml import etree

from .completion import attributes_for
from .facts import DIRECTIVES


_XS = "http://www.w3.org/2001/XMLSchema"
_NATIVE_TAGS = {"textui.widgets.split.Pane": "pane", "textui.widgets.navigation.NavItem": "nav-item"}


def _add(parent: etree._Element, tag: str, **attributes: str) -> etree._Element:
    return etree.SubElement(parent, f"{{{_XS}}}{tag}", attributes)


def _attribute(parent: etree._Element, name: str, spec: dict) -> None:
    attr = _add(parent, "attribute", name=name, use="required" if spec["required"] else "optional")
    value_type = spec["type"]
    literals = value_type.get("values")
    if literals or value_type["type"] == "integer":
        restriction = _add(_add(attr, "simpleType"), "restriction", base="xs:string")
        if literals:
            for value in literals:
                _add(restriction, "enumeration", value=value)
        else:
            _add(restriction, "pattern", value=r"[+-]?\p{Nd}+")
    else:
        attr.set("type", "xs:string")


def _children(parent: etree._Element, tags: list[str], minimum: int = 0, maximum: int | None = None) -> None:
    if not tags:
        return
    choice = _add(parent, "choice", minOccurs=str(minimum), maxOccurs="unbounded" if maximum is None else str(maximum))
    for tag in tags:
        _add(choice, "element", ref=tag)


def _directives(root: etree._Element, *, authoring: bool) -> None:
    for tag in ("script", "include"):
        if tag == "include" and not authoring:
            continue
        type_ = _add(_add(root, "element", name=tag), "complexType")
        _attribute(type_, "src", {"type": {"type": "string"}, "required": True})
    style = _add(_add(root, "element", name="style"), "complexType", mixed="true")
    style_directive = next(directive for directive in DIRECTIVES if directive["tag"] == "style")
    for name, attribute in style_directive["attributes"].items():
        _attribute(style, name, attribute)
    if authoring:
        component = _add(_add(root, "element", name="component"), "complexType")
        # Template bodies contain placeholders whose eventual types depend on
        # instance properties. Do not apply literal built-in types here.
        _add(_add(component, "sequence"), "any", minOccurs="0", maxOccurs="unbounded", processContents="skip")
        _add(component, "anyAttribute", processContents="skip")
        slot = _add(_add(root, "element", name="slot"), "complexType")
        _add(_add(slot, "sequence"), "any", minOccurs="0", maxOccurs="unbounded", processContents="skip")
        _attribute(slot, "name", {"type": {"type": "string"}, "required": False})


def schema(description: dict, *, authoring: bool = False) -> str:
    root = etree.Element(f"{{{_XS}}}schema", nsmap={"xs": _XS}, elementFormDefault="unqualified")
    documentation = _add(_add(root, "annotation"), "documentation")
    documentation.text = (
        "Generated by textui spec. "
        + ("Permissive authoring profile: widget bodies, aliases and templates require textui check --static. " if authoring
           else "Strict built-in profile without includes or after expansion; use textui check --static for projects. ")
        + "See docs/editors.md and docs/markup-reference.md for schema limitations. No target namespace."
    )
    components = description["components"]
    general = []
    roots = []
    for component in components:
        parents = [rule for rule in component["content"]["rules"] if rule["rule"] == "parent"]
        if not parents:
            general.append(component["tag"])
            roots.append(component["tag"])
        elif any(rule["root_only"] for rule in parents):
            roots.append(component["tag"])
    for component in components:
        tag = component["tag"]
        type_ = _add(_add(root, "element", name=tag), "complexType")
        if component["text_policy"] != "none":
            type_.set("mixed", "true")
        rules = component["content"]["rules"]
        if component["content"]["policy"] == "widgets":
            if authoring:
                _add(_add(type_, "sequence"), "any", minOccurs="0", maxOccurs="unbounded", processContents="skip")
            else:
                count = next((rule for rule in rules if rule["rule"] in {"count", "native-children"}), {})
                only = next((rule for rule in rules if rule["rule"] == "only"), None)
                native = next((rule for rule in rules if rule["rule"] == "native-children"), None)
                sequence = next((rule for rule in rules if rule["rule"] == "sequence"), None)
                if sequence:
                    ordered = _add(type_, "sequence")
                    for group in sequence["groups"]:
                        _add(ordered, "element", ref=group["tag"], minOccurs="0", maxOccurs="unbounded")
                elif any(rule["rule"] == "unique-slots" for rule in rules):
                    all_ = _add(type_, "all")
                    for child in only["allowed"]:
                        _add(all_, "element", ref=child["tag"], minOccurs="0")
                else:
                    tags = ([child["tag"] for child in only["allowed"]] if only else
                            [_NATIVE_TAGS[native["widget_type"]]] if native else general)
                    _children(type_, tags, count.get("minimum", 0), count.get("maximum"))
        for name, spec in attributes_for(component, description["common_attributes"]).items():
            _attribute(type_, name, spec)
        for name in component["events"]:
            _add(type_, "attribute", name=f"on-{name}", type="xs:string")
    _directives(root, authoring=authoring)
    ui = _add(_add(root, "element", name="ui"), "complexType")
    if authoring:
        # An alias may shadow *any* built-in name. Lax validation would apply
        # the built-in type to such an instance and reject valid properties or
        # slot children. A project-agnostic XSD cannot resolve that scope.
        _add(_add(ui, "sequence"), "any", minOccurs="0", maxOccurs="unbounded", processContents="skip")
    else:
        _children(ui, [*roots, "style", "script"])
    return etree.tostring(root, encoding="unicode", pretty_print=True).rstrip() + "\n"
